export const DEFAULT_AUTHORITIES = [
  {
    id: 'authority-1',
    name: 'Municipal Services',
    category: 'Public Infrastructure',
    description: 'Configurable sample service directory — not official government data.',
    contactInfo: 'Service desk: local civic office',
    area: 'Citywide',
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'authority-2',
    name: 'Waste Management',
    category: 'Garbage',
    description: 'Configurable sample service directory — not official government data.',
    contactInfo: 'Waste services desk',
    area: 'Citywide',
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'authority-3',
    name: 'Water & Sanitation',
    category: 'Water',
    description: 'Configurable sample service directory — not official government data.',
    contactInfo: 'Water services desk',
    area: 'Local area',
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'authority-4',
    name: 'Roads / Public Works',
    category: 'Road Damage',
    description: 'Configurable sample service directory — not official government data.',
    contactInfo: 'Road maintenance desk',
    area: 'Citywide',
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'authority-5',
    name: 'Drainage / Sanitation',
    category: 'Drainage',
    description: 'Configurable sample service directory — not official government data.',
    contactInfo: 'Drainage and sanitation desk',
    area: 'Local area',
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]
