name = "citycare-ai"
compatibility_date = "2026-10-03"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "citycare-db"
database_id = "d70062fe-708b-4b52-a111-9f1e3dfe841c"
