name = "citycare-ai"
main = "src/worker.ts"
compatibility_date = "2026-10-03"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/api", "/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "citycare-db"
database_id = "d70062fe-708b-4b52-a111-9f1e3dfe841c"
